//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibDesktopApplication.EArsivWsService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class EArsivFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private System.Nullable<int> codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", ConfigurationName="EArsivWsService.EArsivWs")]
    public interface EArsivWs {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendDocumentFile", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GibDesktopApplication.EArsivWsService.EArsivFault), Action="urn:SendDocumentFile", Name="EArsivFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GibDesktopApplication.EArsivWsService.sendDocumentFileResponse sendDocumentFile(GibDesktopApplication.EArsivWsService.sendDocumentFile request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendDocumentFile", ReplyAction="*")]
        System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.sendDocumentFileResponse> sendDocumentFileAsync(GibDesktopApplication.EArsivWsService.sendDocumentFile request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetBatchStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GibDesktopApplication.EArsivWsService.EArsivFault), Action="urn:GetBatchStatus", Name="EArsivFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(GibDesktopApplication.EArsivWsService.InterruptedException), Action="urn:GetBatchStatus", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GibDesktopApplication.EArsivWsService.getBatchStatusResponse getBatchStatus(GibDesktopApplication.EArsivWsService.getBatchStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetBatchStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.getBatchStatusResponse> getBatchStatusAsync(GibDesktopApplication.EArsivWsService.getBatchStatus request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetUserList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(GibDesktopApplication.EArsivWsService.EArsivFault), Action="urn:GetUserList", Name="EArsivFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GibDesktopApplication.EArsivWsService.getUserListResponse getUserList(GibDesktopApplication.EArsivWsService.getUserList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.getUserListResponse> getUserListAsync(GibDesktopApplication.EArsivWsService.getUserList request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDocumentFile", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class sendDocumentFile {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GibDesktopApplication.EArsivWsService.attachment Attachment;
        
        public sendDocumentFile() {
        }
        
        public sendDocumentFile(GibDesktopApplication.EArsivWsService.attachment Attachment) {
            this.Attachment = Attachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDocumentFileResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class sendDocumentFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendDocumentFileResponse() {
        }
        
        public sendDocumentFileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/")]
    public partial class durum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string durumAciklamaField;
        
        private int durumKoduField;
        
        private string paketIdField;
        
        private string tCKimlikNoField;
        
        private string vergiKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string durumAciklama {
            get {
                return this.durumAciklamaField;
            }
            set {
                this.durumAciklamaField = value;
                this.RaisePropertyChanged("durumAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int durumKodu {
            get {
                return this.durumKoduField;
            }
            set {
                this.durumKoduField = value;
                this.RaisePropertyChanged("durumKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string paketId {
            get {
                return this.paketIdField;
            }
            set {
                this.paketIdField = value;
                this.RaisePropertyChanged("paketId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TCKimlikNo {
            get {
                return this.tCKimlikNoField;
            }
            set {
                this.tCKimlikNoField = value;
                this.RaisePropertyChanged("TCKimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vergiKimlikNo {
            get {
                return this.vergiKimlikNoField;
            }
            set {
                this.vergiKimlikNoField = value;
                this.RaisePropertyChanged("vergiKimlikNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBatchStatus", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getBatchStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paketId;
        
        public getBatchStatus() {
        }
        
        public getBatchStatus(string paketId) {
            this.paketId = paketId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBatchStatusResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getBatchStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GibDesktopApplication.EArsivWsService.durum @return;
        
        public getBatchStatusResponse() {
        }
        
        public getBatchStatusResponse(GibDesktopApplication.EArsivWsService.durum @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserList", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getUserList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type;
        
        public getUserList() {
        }
        
        public getUserList(string type) {
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserListResponse", WrapperNamespace="http://earsiv.vedop3.ggm.gov.org/", IsWrapped=true)]
    public partial class getUserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://earsiv.vedop3.ggm.gov.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GibDesktopApplication.EArsivWsService.attachment @return;
        
        public getUserListResponse() {
        }
        
        public getUserListResponse(GibDesktopApplication.EArsivWsService.attachment @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EArsivWsChannel : GibDesktopApplication.EArsivWsService.EArsivWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EArsivWsClient : System.ServiceModel.ClientBase<GibDesktopApplication.EArsivWsService.EArsivWs>, GibDesktopApplication.EArsivWsService.EArsivWs {
        
        public EArsivWsClient() {
        }
        
        public EArsivWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EArsivWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EArsivWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EArsivWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GibDesktopApplication.EArsivWsService.sendDocumentFileResponse GibDesktopApplication.EArsivWsService.EArsivWs.sendDocumentFile(GibDesktopApplication.EArsivWsService.sendDocumentFile request) {
            return base.Channel.sendDocumentFile(request);
        }
        
        public string sendDocumentFile(GibDesktopApplication.EArsivWsService.attachment Attachment) {
            GibDesktopApplication.EArsivWsService.sendDocumentFile inValue = new GibDesktopApplication.EArsivWsService.sendDocumentFile();
            inValue.Attachment = Attachment;
            GibDesktopApplication.EArsivWsService.sendDocumentFileResponse retVal = ((GibDesktopApplication.EArsivWsService.EArsivWs)(this)).sendDocumentFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.sendDocumentFileResponse> GibDesktopApplication.EArsivWsService.EArsivWs.sendDocumentFileAsync(GibDesktopApplication.EArsivWsService.sendDocumentFile request) {
            return base.Channel.sendDocumentFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.sendDocumentFileResponse> sendDocumentFileAsync(GibDesktopApplication.EArsivWsService.attachment Attachment) {
            GibDesktopApplication.EArsivWsService.sendDocumentFile inValue = new GibDesktopApplication.EArsivWsService.sendDocumentFile();
            inValue.Attachment = Attachment;
            return ((GibDesktopApplication.EArsivWsService.EArsivWs)(this)).sendDocumentFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GibDesktopApplication.EArsivWsService.getBatchStatusResponse GibDesktopApplication.EArsivWsService.EArsivWs.getBatchStatus(GibDesktopApplication.EArsivWsService.getBatchStatus request) {
            return base.Channel.getBatchStatus(request);
        }
        
        public GibDesktopApplication.EArsivWsService.durum getBatchStatus(string paketId) {
            GibDesktopApplication.EArsivWsService.getBatchStatus inValue = new GibDesktopApplication.EArsivWsService.getBatchStatus();
            inValue.paketId = paketId;
            GibDesktopApplication.EArsivWsService.getBatchStatusResponse retVal = ((GibDesktopApplication.EArsivWsService.EArsivWs)(this)).getBatchStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.getBatchStatusResponse> GibDesktopApplication.EArsivWsService.EArsivWs.getBatchStatusAsync(GibDesktopApplication.EArsivWsService.getBatchStatus request) {
            return base.Channel.getBatchStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.getBatchStatusResponse> getBatchStatusAsync(string paketId) {
            GibDesktopApplication.EArsivWsService.getBatchStatus inValue = new GibDesktopApplication.EArsivWsService.getBatchStatus();
            inValue.paketId = paketId;
            return ((GibDesktopApplication.EArsivWsService.EArsivWs)(this)).getBatchStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GibDesktopApplication.EArsivWsService.getUserListResponse GibDesktopApplication.EArsivWsService.EArsivWs.getUserList(GibDesktopApplication.EArsivWsService.getUserList request) {
            return base.Channel.getUserList(request);
        }
        
        public GibDesktopApplication.EArsivWsService.attachment getUserList(string type) {
            GibDesktopApplication.EArsivWsService.getUserList inValue = new GibDesktopApplication.EArsivWsService.getUserList();
            inValue.type = type;
            GibDesktopApplication.EArsivWsService.getUserListResponse retVal = ((GibDesktopApplication.EArsivWsService.EArsivWs)(this)).getUserList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.getUserListResponse> GibDesktopApplication.EArsivWsService.EArsivWs.getUserListAsync(GibDesktopApplication.EArsivWsService.getUserList request) {
            return base.Channel.getUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<GibDesktopApplication.EArsivWsService.getUserListResponse> getUserListAsync(string type) {
            GibDesktopApplication.EArsivWsService.getUserList inValue = new GibDesktopApplication.EArsivWsService.getUserList();
            inValue.type = type;
            return ((GibDesktopApplication.EArsivWsService.EArsivWs)(this)).getUserListAsync(inValue);
        }
    }
}
